## Filter out matches pre 2006, use 4 slams all 9 atp 1000,
## Clay: RG, MC, MA, RM, BAR, MUN, HAM, RIO
## Hard: AO, USO, PAR, IW, MIA, CIN, TOR/MONT, SHA
## Grass: WIM, HALLE, LON, HERTOGENBOSCH, MALLORCA, EASTBOURNE

In [ ]:
import pandas as pd
from pathlib import Path

RAW_DIRECTORY = Path("../data/raw/sackmann")

tour_keep = ["Wimbledon", "Roland Garros", "US Open", "Australian Open", "Madrid", "Montecarlo",
          "Rome", "Barcelona", "Munich", "Hamburg", "Rio de Janeiro", "Shanghai", "Paris", "Indian Wells",
          "Cincinnati", "Miami", "Toronto", "Montreal", "Halle", "Queen's Club", "Monte Carlo Masters", "Paris Masters",
          "Cincinnati Masters", "Indian Wells Master", "Miami Masters", "Rome Masters", "Madrid Masters",
          "Canada Masters", "Shangai Masters", "s Hertogenbosch", "Mallorca", "Eastbourne"]

files = sorted(RAW_DIRECTORY.glob("atp_matches_*.csv"))
matches = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)

In [33]:
matches["tourney_date"] = pd.to_datetime(matches["tourney_date"], format="%Y%m%d")
matches = matches[matches["tourney_date"] >= "2006-01-01"]
matches = matches.sort_values("tourney_date", ascending = True)
matches.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
142666,2006-891,Chennai,Hard,32.0,A,2006-01-02,16,103285,2.0,NaN,...,35.0,30.0,22.0,11.0,2.0,3.0,20.0,1440.0,139.0,301.0
140457,2006-339,Adelaide,Hard,32.0,A,2006-01-02,7,104312,NaN,NaN,...,33.0,24.0,11.0,10.0,5.0,8.0,68.0,562.0,82.0,498.0
140456,2006-339,Adelaide,Hard,32.0,A,2006-01-02,6,103598,NaN,NaN,...,40.0,29.0,15.0,10.0,6.0,9.0,47.0,731.0,146.0,286.0
140455,2006-339,Adelaide,Hard,32.0,A,2006-01-02,5,104339,4.0,NaN,...,23.0,15.0,4.0,7.0,4.0,9.0,21.0,1360.0,69.0,558.0
140454,2006-339,Adelaide,Hard,32.0,A,2006-01-02,4,104607,6.0,NaN,...,58.0,43.0,27.0,16.0,5.0,8.0,24.0,1200.0,51.0,692.0

In [34]:
matches = matches[matches["tourney_name"].isin(tour_keep)]
matches.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
142441,2006-580,Australian Open,Hard,128.0,G,2006-01-16,103,103908,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,713.0,81.0,492.0
142445,2006-580,Australian Open,Hard,128.0,G,2006-01-16,107,103990,16.0,NaN,...,50.0,35.0,20.0,14.0,9.0,13.0,19.0,1490.0,22.0,1390.0
142442,2006-580,Australian Open,Hard,128.0,G,2006-01-16,104,103206,25.0,NaN,...,82.0,50.0,12.0,17.0,17.0,26.0,28.0,1080.0,9.0,2175.0
142443,2006-580,Australian Open,Hard,128.0,G,2006-01-16,105,102148,NaN,NaN,...,81.0,51.0,26.0,23.0,5.0,13.0,65.0,580.0,10.0,2050.0
142444,2006-580,Australian Open,Hard,128.0,G,2006-01-16,106,103970,11.0,NaN,...,57.0,31.0,14.0,13.0,7.0,13.0,14.0,1635.0,21.0,1390.0

In [ ]:
matches.to_csv("../data/processed/atp_matches.csv", index = False)